window.dashboardData = {
  "meta": {
    "lastUpdated": "2026-09-12",
    "properties": [
      "14 Lakewood Dr",
      "38 Lakewood Dr",
      "7 Ash Lane",
      "General"
    ],
    "categories": [
      "Contractor Labor",
      "Food",
      "LotRent",
      "Materials",
      "Other",
      "Permits",
      "Purchase Price",
      "Utilities"
    ],
    "payers": [
      "BG Contracting",
      "LLC Bank Account",
      "Sai"
    ],
    "years": [
      2025,
      2026
    ]
  },
  "expenses": [
    {
      "id": "E001",
      "date": "2025-09-10",
      "year": 2025,
      "month": "2025-09",
      "property": "7 Ash Lane",
      "category": "Purchase Price",
      "paidBy": "Sai",
      "amount": 500,
      "notes": "inital deposit",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E002",
      "date": "2025-09-10",
      "year": 2025,
      "month": "2025-09",
      "property": "38 Lakewood Dr",
      "category": "Purchase Price",
      "paidBy": "Sai",
      "amount": 500,
      "notes": "inital deposit",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E003",
      "date": "2025-09-10",
      "year": 2025,
      "month": "2025-09",
      "property": "14 Lakewood Dr",
      "category": "Purchase Price",
      "paidBy": "Sai",
      "amount": 500,
      "notes": "inital deposit",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E004",
      "date": "2025-09-16",
      "year": 2025,
      "month": "2025-09",
      "property": "General",
      "category": "Other",
      "paidBy": "Sai",
      "amount": 520,
      "notes": "LLC formation",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E005",
      "date": "2025-09-27",
      "year": 2025,
      "month": "2025-09",
      "property": "7 Ash Lane",
      "category": "Purchase Price",
      "paidBy": "LLC Bank Account",
      "amount": 15000,
      "notes": "Closing cost, Part of $35,000 bank withdrawal on 2025-09-27; split by property/category",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E006",
      "date": "2025-09-27",
      "year": 2025,
      "month": "2025-09",
      "property": "38 Lakewood Dr",
      "category": "Purchase Price",
      "paidBy": "LLC Bank Account",
      "amount": 18000,
      "notes": "Closing cost, Part of $35,000 bank withdrawal on 2025-09-27; split by property/category",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E007",
      "date": "2025-09-27",
      "year": 2025,
      "month": "2025-09",
      "property": "14 Lakewood Dr",
      "category": "Purchase Price",
      "paidBy": "LLC Bank Account",
      "amount": 1500,
      "notes": "Closing cost, Part of $35,000 bank withdrawal on 2025-09-27; split by property/category",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E008",
      "date": "2025-09-27",
      "year": 2025,
      "month": "2025-09",
      "property": "General",
      "category": "Other",
      "paidBy": "LLC Bank Account",
      "amount": 500,
      "notes": "Attorney Fees for Purchase, Part of $35,000 bank withdrawal on 2025-09-27; split by property/category",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E009",
      "date": "2025-10-14",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 915,
      "notes": "Dumbster",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E010",
      "date": "2025-10-08",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 44.57,
      "notes": "lock+ folding lock-back lnife",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E011",
      "date": "2025-10-09",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E012",
      "date": "2025-10-09",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 100,
      "notes": "1L*5H=5",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E013",
      "date": "2025-10-09",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 3057.26,
      "notes": "12 windows",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E014",
      "date": "2025-10-13",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E015",
      "date": "2025-10-17",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 282,
      "notes": "Dumbster",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E016",
      "date": "2025-10-18",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 531.68,
      "notes": "HomeDepot -paint",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E017",
      "date": "2025-10-18",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 7.97,
      "notes": "Dollar general - carpet arm& harmour",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E018",
      "date": "2025-10-19",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 734.38,
      "notes": "2 doors -Home outlet",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E019",
      "date": "2025-10-22",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "LLC Bank Account",
      "amount": 900,
      "notes": "exterior paint",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E020",
      "date": "2025-10-25",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8H=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E021",
      "date": "2025-10-25",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 399.26,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E022",
      "date": "2025-10-25",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 174.08,
      "notes": "Homedepot =(5.92)",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E023",
      "date": "2025-10-26",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 2.25,
      "notes": "fuel",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E024",
      "date": "2025-10-26",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Food",
      "paidBy": "LLC Bank Account",
      "amount": 8.6,
      "notes": "coke",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E025",
      "date": "2025-10-29",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Food",
      "paidBy": "LLC Bank Account",
      "amount": -7.97,
      "notes": "coke- refund E017",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E026",
      "date": "2025-10-29",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=20",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E027",
      "date": "2025-10-30",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 2500,
      "notes": "Electric- advance- Evgeny Plekhavov",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E028",
      "date": "2025-10-30",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E029",
      "date": "2025-10-31",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E030",
      "date": "2025-10-31",
      "year": 2025,
      "month": "2025-10",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E031",
      "date": "2025-10-31",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 21.11,
      "notes": "HomeDepot -tools = (4.81= (5.92-1.11))",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E032",
      "date": "2025-10-31",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 583.11,
      "notes": "HomeDepot - walls ceiling",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E033",
      "date": "2025-10-31",
      "year": 2025,
      "month": "2025-10",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 4200,
      "notes": "Roof material + install",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E034",
      "date": "2025-11-01",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E035",
      "date": "2025-11-03",
      "year": 2025,
      "month": "2025-11",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 915,
      "notes": "Dumbster",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E036",
      "date": "2025-11-04",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8H=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E037",
      "date": "2025-11-04",
      "year": 2025,
      "month": "2025-11",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E038",
      "date": "2025-11-04",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 283.01,
      "notes": "Homedepot-drywall",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E039",
      "date": "2025-11-05",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "2L*8H+2L*4H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E040",
      "date": "2025-11-06",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 71.95,
      "notes": "Homedepot - PVC",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E041",
      "date": "2025-11-06",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "2L*8H+2L*4H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E042",
      "date": "2025-11-07",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Permits",
      "paidBy": "LLC Bank Account",
      "amount": 900,
      "notes": "plumbing+pressure test",
      "reviewed": "Forest",
      "paid": ""
    },
    {
      "id": "E043",
      "date": "2025-11-07",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 240,
      "notes": "1L*8H+2L*2H=12",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E044",
      "date": "2025-11-08",
      "year": 2025,
      "month": "2025-11",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "2L*4H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E045",
      "date": "2025-11-10",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E046",
      "date": "2025-11-11",
      "year": 2025,
      "month": "2025-11",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E047",
      "date": "2025-11-12",
      "year": 2025,
      "month": "2025-11",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 4200,
      "notes": "Roof material + install",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E048",
      "date": "2025-11-13",
      "year": 2025,
      "month": "2025-11",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 915,
      "notes": "Dumbster",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E049",
      "date": "2025-12-04",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 360,
      "notes": "3L*6H=18",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E050",
      "date": "2025-12-10",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E051",
      "date": "2025-12-10",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 686.68,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E052",
      "date": "2025-12-10",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 202.57,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E053",
      "date": "2025-12-11",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 128,
      "notes": "Dumbster",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E054",
      "date": "2025-12-19",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E055",
      "date": "2025-12-19",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 763.98,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E056",
      "date": "2025-12-20",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 279.41,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E057",
      "date": "2025-12-20",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 360,
      "notes": "3L*6H=18",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E058",
      "date": "2025-12-22",
      "year": 2025,
      "month": "2025-12",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 1312.99,
      "notes": "Oct-dec2025",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E059",
      "date": "2025-12-22",
      "year": 2025,
      "month": "2025-12",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 1312.99,
      "notes": "Oct-dec2025",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E060",
      "date": "2025-12-22",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 1312.99,
      "notes": "Oct-dec2025",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E061",
      "date": "2025-12-22",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 240,
      "notes": "2L*6H=12",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E062",
      "date": "2025-12-24",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 743.62,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E063",
      "date": "2025-12-24",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E064",
      "date": "2025-12-24",
      "year": 2025,
      "month": "2025-12",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E065",
      "date": "2025-12-26",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 752.31,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E066",
      "date": "2025-12-26",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 126.44,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E067",
      "date": "2025-12-26",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E068",
      "date": "2025-12-26",
      "year": 2025,
      "month": "2025-12",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 120,
      "notes": "2L*3H=6",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E069",
      "date": "2025-12-29",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Food",
      "paidBy": "LLC Bank Account",
      "amount": 10.08,
      "notes": "coke",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E070",
      "date": "2025-12-29",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8H=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E071",
      "date": "2025-12-29",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 274.5,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E072",
      "date": "2025-12-29",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 44.42,
      "notes": "Tractor Supply",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E073",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E074",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E075",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 20,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E076",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 20,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E077",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "14 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 20,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E078",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 83.52,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "E079",
      "date": "2025-12-31",
      "year": 2025,
      "month": "2025-12",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 66.65,
      "notes": "Homedepot- partial",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F001",
      "date": "2026-01-02",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 4685.02,
      "notes": "Homedepot-7ash&38Lake floor",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F002",
      "date": "2026-01-03",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F003",
      "date": "2026-01-03",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 33.21,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F004",
      "date": "2026-01-05",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F005",
      "date": "2026-01-06",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F006",
      "date": "2026-01-07",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F007",
      "date": "2026-01-08",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F008",
      "date": "2026-01-08",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 63.73,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F009",
      "date": "2026-01-09",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F010",
      "date": "2026-01-09",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 31.09,
      "notes": "Propane",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F011",
      "date": "2026-01-09",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 150.82,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F012",
      "date": "2026-01-09",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 2056.85,
      "notes": "Homedepot -includes 38 lakewood",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F013",
      "date": "2026-01-10",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F014",
      "date": "2026-01-10",
      "year": 2026,
      "month": "2026-01",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 420,
      "notes": "3L*7H=21",
      "reviewed": "confirm whatsapp 1/12 invoices",
      "paid": ""
    },
    {
      "id": "F015",
      "date": "2026-01-10",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 51.52,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F016",
      "date": "2026-01-13",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F017",
      "date": "2026-01-13",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 203.88,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F018",
      "date": "2026-01-14",
      "year": 2026,
      "month": "2026-01",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 163.5,
      "notes": "lenox transfer station-trashdump",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F019",
      "date": "2026-01-14",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F020",
      "date": "2026-01-15",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 240,
      "notes": "2L*3H=6",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F021",
      "date": "2026-01-15",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 240,
      "notes": "2L*3H=6",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F022",
      "date": "2026-01-16",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F023",
      "date": "2026-01-17",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F024",
      "date": "2026-01-17",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F025",
      "date": "2026-01-19",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 132.49,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F026",
      "date": "2026-01-19",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F027",
      "date": "2026-01-20",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F028",
      "date": "2026-01-20",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 89.12,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F029",
      "date": "2026-01-20",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 42.62,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F030",
      "date": "2026-01-21",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F031",
      "date": "2026-01-22",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 92.41,
      "notes": "CO2-carrhardware",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F032",
      "date": "2026-01-22",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 124.65,
      "notes": "Homedepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F033",
      "date": "2026-01-22",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F034",
      "date": "2026-01-23",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F035",
      "date": "2026-01-23",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 66.73,
      "notes": "transformer",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F036",
      "date": "2026-01-27",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F037",
      "date": "2026-01-28",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F038",
      "date": "2026-01-29",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F039",
      "date": "2026-01-29",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 438.56,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F040",
      "date": "2026-01-29",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 82.56,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F041",
      "date": "2026-01-29",
      "year": 2026,
      "month": "2026-01",
      "property": "General",
      "category": "Other",
      "paidBy": "LLC Bank Account",
      "amount": 5.23,
      "notes": "tax-1099",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F042",
      "date": "2026-01-30",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F043",
      "date": "2026-02-02",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F044",
      "date": "2026-02-02",
      "year": 2026,
      "month": "2026-02",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F045",
      "date": "2026-02-02",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F046",
      "date": "2026-01-30",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F047",
      "date": "2026-01-30",
      "year": 2026,
      "month": "2026-01",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 20.29,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F048",
      "date": "2026-01-30",
      "year": 2026,
      "month": "2026-01",
      "property": "14 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F049",
      "date": "2026-01-31",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F050",
      "date": "2026-01-31",
      "year": 2026,
      "month": "2026-01",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F051",
      "date": "2026-01-31",
      "year": 2026,
      "month": "2026-01",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 4722.3,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F052",
      "date": "2026-02-01",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 328.77,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F053",
      "date": "2026-02-04",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 619.04,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F054",
      "date": "2026-02-04",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F055",
      "date": "2026-02-05",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 166.18,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F056",
      "date": "2026-02-05",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F057",
      "date": "2026-02-06",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 45.41,
      "notes": "Amazon-doorknobs",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F058",
      "date": "2026-02-06",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F059",
      "date": "2026-02-06",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 56.58,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F060",
      "date": "2026-02-07",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 513.64,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F061",
      "date": "2026-02-09",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 369.16,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F062",
      "date": "2026-02-09",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F063",
      "date": "2026-02-10",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 446.71,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F064",
      "date": "2026-02-10",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F065",
      "date": "2026-02-12",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 45.47,
      "notes": "Tractor Supply",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F066",
      "date": "2026-02-12",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F067",
      "date": "2026-02-13",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 253.25,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F068",
      "date": "2026-02-13",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 1045.49,
      "notes": "Dettinger lumber company",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F069",
      "date": "2026-02-13",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F070",
      "date": "2026-02-13",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 1866.81,
      "notes": "Appliances -7Ash ln",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F071",
      "date": "2026-02-14",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F072",
      "date": "2026-02-16",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8-32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F073",
      "date": "2026-02-16",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 256.9,
      "notes": "Kobie-Plumbing",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F074",
      "date": "2026-02-17",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 164.6,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F075",
      "date": "2026-02-17",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F076",
      "date": "2026-02-17",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 738.44,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F077",
      "date": "2026-02-18",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F078",
      "date": "2026-02-18",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 52.89,
      "notes": "Tractor Supply",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F079",
      "date": "2026-02-18",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 39.26,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F080",
      "date": "2026-02-18",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 201.1,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F081",
      "date": "2026-02-19",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F082",
      "date": "2026-02-20",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 1068.37,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F083",
      "date": "2026-02-20",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F084",
      "date": "2026-02-20",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 16.96,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F085",
      "date": "2026-02-20",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 115.81,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F086",
      "date": "2026-02-21",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F087",
      "date": "2026-02-23",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 74.73,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F088",
      "date": "2026-02-24",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F089",
      "date": "2026-02-24",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 461.99,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F090",
      "date": "2026-02-25",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F091",
      "date": "2026-02-25",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 215.88,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F092",
      "date": "2026-02-26",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F093",
      "date": "2026-02-26",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 79.5,
      "notes": "Amazon-faucet",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F094",
      "date": "2026-02-26",
      "year": 2026,
      "month": "2026-02",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 136.49,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F095",
      "date": "2026-02-26",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 124.06,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F096",
      "date": "2026-02-27",
      "year": 2026,
      "month": "2026-02",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 960,
      "notes": "6L*8=48",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F097",
      "date": "2026-02-27",
      "year": 2026,
      "month": "2026-02",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 27.6,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F098",
      "date": "2026-02-28",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8H=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F099",
      "date": "2026-02-28",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 130.5,
      "notes": "Trash dump",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F100",
      "date": "2026-02-28",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 32.88,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F101",
      "date": "2026-02-28",
      "year": 2026,
      "month": "2026-02",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 63.55,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F102",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F103",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 48.16,
      "notes": "Tractor Supply",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F104",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 9.48,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F105",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 15.99,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F106",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 9.48,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F107",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F108",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F109",
      "date": "2026-03-02",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F110",
      "date": "2026-03-03",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F111",
      "date": "2026-03-04",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F112",
      "date": "2026-03-04",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Permits",
      "paidBy": "BG Contracting",
      "amount": 36.4,
      "notes": "Building inspection",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F113",
      "date": "2026-03-05",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F114",
      "date": "2026-03-06",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F115",
      "date": "2026-03-06",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 221.95,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F116",
      "date": "2026-03-08",
      "year": 2026,
      "month": "2026-03",
      "property": "General",
      "category": "Other",
      "paidBy": "LLC Bank Account",
      "amount": 300,
      "notes": "2025 TAX- SHILPI",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F117",
      "date": "2026-03-10",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F118",
      "date": "2026-03-10",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 292.72,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F119",
      "date": "2026-03-16",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Permits",
      "paidBy": "LLC Bank Account",
      "amount": 400,
      "notes": "PLUMBING FOREST",
      "reviewed": "forest",
      "paid": ""
    },
    {
      "id": "F120",
      "date": "2026-03-16",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 1000,
      "notes": "Boiller market place cash",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F121",
      "date": "2026-03-16",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 160,
      "notes": "1L*8H=8",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F122",
      "date": "2026-03-17",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 44.07,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F123",
      "date": "2026-03-17",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 320,
      "notes": "2L*8H=16",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F124",
      "date": "2026-03-18",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F125",
      "date": "2026-03-19",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 640,
      "notes": "4L*8H=32",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F126",
      "date": "2026-03-19",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 73.63,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F127",
      "date": "2026-03-19",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 117.14,
      "notes": "concrete",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F128",
      "date": "2026-03-19",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 121.4,
      "notes": "Amazon - porch lights",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F129",
      "date": "2026-03-19",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 36.06,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F130",
      "date": "2026-03-20",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 800,
      "notes": "5L*8H=40",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F131",
      "date": "2026-03-28",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 163.27,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F132",
      "date": "2026-03-24",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 2409.73,
      "notes": "Furnance ( Bobs+lakewood)",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F133",
      "date": "2026-03-26",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 600,
      "notes": "Kobie -plumbing",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F134",
      "date": "2026-03-31",
      "year": 2026,
      "month": "2026-03",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 7.5,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F135",
      "date": "2026-03-31",
      "year": 2026,
      "month": "2026-03",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 9.35,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F136",
      "date": "2026-03-31",
      "year": 2026,
      "month": "2026-03",
      "property": "14 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 7.5,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F137",
      "date": "2026-04-01",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F138",
      "date": "2026-04-01",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F139",
      "date": "2026-04-01",
      "year": 2026,
      "month": "2026-04",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 522.99,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F140",
      "date": "2026-04-11",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Contractor Labor",
      "paidBy": "BG Contracting",
      "amount": 480,
      "notes": "3L*8H=24",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F141",
      "date": "2026-04-11",
      "year": 2026,
      "month": "2026-04",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 2088.03,
      "notes": "HomeDepot-cabinets",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F142",
      "date": "2026-04-12",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 316.5,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F143",
      "date": "2026-04-16",
      "year": 2026,
      "month": "2026-04",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 359.13,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F144",
      "date": "2026-04-21",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 106.09,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F145",
      "date": "2026-04-29",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": -1158,
      "notes": "refund for 1/9/26 homedepot-Pending",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F146",
      "date": "2026-04-27",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 126.35,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F147",
      "date": "2026-04-28",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 41.01,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F148",
      "date": "2026-04-29",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 500.16,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F149",
      "date": "2026-04-29",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 906.11,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F150",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 232.79,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F151",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 90.89,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F152",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 563.26,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F153",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 9.29,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F154",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 8.17,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F155",
      "date": "2026-04-30",
      "year": 2026,
      "month": "2026-04",
      "property": "14 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 3.75,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F156",
      "date": "2026-05-01",
      "year": 2026,
      "month": "2026-05",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F157",
      "date": "2026-05-01",
      "year": 2026,
      "month": "2026-05",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F158",
      "date": "2026-05-01",
      "year": 2026,
      "month": "2026-05",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F159",
      "date": "2026-05-13",
      "year": 2026,
      "month": "2026-05",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 217.04,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F160",
      "date": "2026-05-16",
      "year": 2026,
      "month": "2026-05",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 314.17,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F161",
      "date": "2026-05-28",
      "year": 2026,
      "month": "2026-05",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 53.37,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F162",
      "date": "2026-05-29",
      "year": 2026,
      "month": "2026-05",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10.98,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F163",
      "date": "2026-05-29",
      "year": 2026,
      "month": "2026-05",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F164",
      "date": "2026-06-01",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F165",
      "date": "2026-06-01",
      "year": 2026,
      "month": "2026-06",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F166",
      "date": "2026-06-01",
      "year": 2026,
      "month": "2026-06",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F167",
      "date": "2026-06-03",
      "year": 2026,
      "month": "2026-06",
      "property": "38 Lakewood Dr",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 1672.23,
      "notes": "Furnance",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F168",
      "date": "2026-06-08",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 9.87,
      "notes": "Amazon",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F169",
      "date": "2026-06-10",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 144.57,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F170",
      "date": "2026-06-16",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "BG Contracting",
      "amount": 200.72,
      "notes": "HomeDepot",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F171",
      "date": "2026-06-20",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 27.22,
      "notes": "Amazon- returned partial( 46.44-19.22)",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F172",
      "date": "2026-06-30",
      "year": 2026,
      "month": "2026-06",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F173",
      "date": "2026-07-01",
      "year": 2026,
      "month": "2026-07",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F174",
      "date": "2026-07-01",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F175",
      "date": "2026-07-01",
      "year": 2026,
      "month": "2026-07",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F176",
      "date": "2026-07-01",
      "year": 2026,
      "month": "2026-07",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F177",
      "date": "2026-07-06",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Permits",
      "paidBy": "Sai",
      "amount": 500,
      "notes": "paid forest for water heater permit",
      "reviewed": "forest",
      "paid": ""
    },
    {
      "id": "F178",
      "date": "2026-07-10",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 30.8,
      "notes": "Amaxon-Heat Tape",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F179",
      "date": "2026-07-12",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 41.11,
      "notes": "Amazon-lock box",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F180",
      "date": "2026-07-16",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 77.18,
      "notes": "Amazon -bathroom",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F181",
      "date": "2026-07-17",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 55.24,
      "notes": "Amazon- Heat tape",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F182",
      "date": "2026-07-25",
      "year": 2026,
      "month": "2026-07",
      "property": "7 Ash Lane",
      "category": "Materials",
      "paidBy": "Sai",
      "amount": 23.35,
      "notes": "Carr Hardware -light bulbs",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F183",
      "date": "2026-08-03",
      "year": 2026,
      "month": "2026-08",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10.34,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F184",
      "date": "2026-08-03",
      "year": 2026,
      "month": "2026-08",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10.97,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F185",
      "date": "2026-08-03",
      "year": 2026,
      "month": "2026-08",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F186",
      "date": "2026-08-03",
      "year": 2026,
      "month": "2026-08",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F187",
      "date": "2026-08-03",
      "year": 2026,
      "month": "2026-08",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F188",
      "date": "2026-08-07",
      "year": 2026,
      "month": "2026-08",
      "property": "14 Lakewood Dr",
      "category": "Materials",
      "paidBy": "LLC Bank Account",
      "amount": 127.46,
      "notes": "HomeDepot-landscaping",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F189",
      "date": "2026-09-01",
      "year": 2026,
      "month": "2026-09",
      "property": "7 Ash Lane",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F190",
      "date": "2026-09-01",
      "year": 2026,
      "month": "2026-09",
      "property": "38 Lakewood Dr",
      "category": "Utilities",
      "paidBy": "LLC Bank Account",
      "amount": 10.99,
      "notes": "Eversource",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F191",
      "date": "2026-09-01",
      "year": 2026,
      "month": "2026-09",
      "property": "7 Ash Lane",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F192",
      "date": "2026-09-01",
      "year": 2026,
      "month": "2026-09",
      "property": "38 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    },
    {
      "id": "F193",
      "date": "2026-09-01",
      "year": 2026,
      "month": "2026-09",
      "property": "14 Lakewood Dr",
      "category": "LotRent",
      "paidBy": "LLC Bank Account",
      "amount": 523.35,
      "notes": "",
      "reviewed": "",
      "paid": ""
    }
  ],
  "vendorPayments": [
    {
      "id": "VP001",
      "date": "2025-11-07",
      "year": 2025,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 4200,
      "bankDescription": "bank transfer",
      "notes": "G&S, 38 lakewood roof"
    },
    {
      "id": "VP002",
      "date": "2025-12-04",
      "year": 2025,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 4200,
      "bankDescription": "bank transfer",
      "notes": "G&S, 7 Ash ln roof"
    },
    {
      "id": "VP003",
      "date": "2026-01-13",
      "year": 2026,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 4457.26,
      "bankDescription": "bank transfer",
      "notes": "G&S invoice #410"
    },
    {
      "id": "VP004",
      "date": "2026-01-13",
      "year": 2026,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 980,
      "bankDescription": "bank transfer",
      "notes": "G&S invoice #408"
    },
    {
      "id": "VP005",
      "date": "2026-02-20",
      "year": 2026,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 12500,
      "bankDescription": "bank transfer",
      "notes": "G&S invoice #423"
    },
    {
      "id": "VP006",
      "date": "2026-05-01",
      "year": 2026,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 1000,
      "bankDescription": "Cash Withdraw",
      "notes": "furnance marketplace"
    },
    {
      "id": "VP007",
      "date": "2026-05-03",
      "year": 2026,
      "paidFrom": "LLC Bank Account",
      "paidTo": "BG Contracting",
      "amount": 11000,
      "bankDescription": "bank transfer",
      "notes": "G&S invoice #427"
    }
  ],
  "contributions": [
    {
      "date": "2025-09-17",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 20,
      "notes": "Inital deposit Checking+ Savings. Greylock bus account"
    },
    {
      "date": "2025-09-17",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 1000,
      "notes": "cash depost into bus checking account"
    },
    {
      "date": "2025-09-25",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 6000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-09-25",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 6000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-09-27",
      "year": 2025,
      "member": "Malila",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 12340,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-09-27",
      "year": 2025,
      "member": "Paul",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 12340,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-10-08",
      "year": 2025,
      "member": "Paul",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 1000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-10-08",
      "year": 2025,
      "member": "Malila",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 1000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-10-25",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-10-27",
      "year": 2025,
      "member": "Malila",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-10-27",
      "year": 2025,
      "member": "Paul",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-12-04",
      "year": 2025,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-12-04",
      "year": 2025,
      "member": "Paul",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2025-12-06",
      "year": 2025,
      "member": "Malila",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 5000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2026-08-10",
      "year": 2026,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 1000,
      "notes": "Greylock deposit"
    },
    {
      "date": "2026-09-12",
      "year": 2026,
      "member": "Sai",
      "property": "General",
      "type": "Capital Contribution",
      "amount": 1000,
      "notes": "Greylock deposit"
    }
  ]
};
